# Deploys after CI

name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types: 
        - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          cd /var/www/mediamonks
          php artisan down
          git checkout -f
          git pull
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan optimize
          php artisan up
          npm install && npm run build
          
