# Runs unit tests on every push

name: CI
on:
  push:
    branches: [main]

jobs:
  laravel-tests:
    name: PHP tests
    runs-on: ubuntu-20.04
    steps:

      - name: Setting MySql 8
        run: |
          echo -e "Enable LOAD DATA LOCAL INFILE in my.cnf\n"
          echo -e "SETTING secure-file-priv TO EMPTY STRING\n"
          echo -e "[mysqld]\nsecure-file-priv=''" | sudo tee -a /etc/mysql/my.cnf
          echo -e "SETTING local_infile TO ON\n"
          echo -e "[mysqld]\nlocal_infile='ON'" | sudo tee -a /etc/mysql/my.cnf
          echo -e "Start MYSQL service, it is off by default\n"
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          echo -e "Creating testing Database\n"
          mysql --host 127.0.0.1 -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS testing;'
          echo -e "Check new settings\n"
          mysql --host 127.0.0.1 -uroot -proot -e "SELECT @@global.secure_file_priv, @@global.local_infile"

      - name: Setting PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - uses: actions/checkout@v3
      
      - name: Copy .env
        run: cp .env.ci .env

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --ansi
      
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        
      - name: Install NPM dependencies
        run: npm ci

      - name: Run vite build
        run: npm run build

      - name: Run migrations and seeders
        run: php artisan migrate:fresh --seed --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --parallel

      - name: Install Latest Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk

#  static-analysis:
#    name: Static analysis
#    runs-on: ubuntu-20.04
#    steps:
#
#      - uses: actions/checkout@v3
#      - name: Setting PHP 8.1
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.1'
#          tools: phpstan
#
#      - name: Install Dependencies
#        run: composer install --prefer-dist --no-interaction --ansi
#
#      - name: Run PHPStan
#        run: vendor/bin/phpstan analyse app --level=max --no-progress --error-format=github

#  prettier:
#    name: Prettier
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#      - run: yarn install
#
#      - name: Run Prettier
#        run: npx prettier --check .